ln -sf ../crypto/md4/md4.c ./apps/md4.c
ln -sf ../../crypto/aes/aes.h ./include/openssl/aes.h
ln -sf ../../crypto/asn1/asn1.h ./include/openssl/asn1.h
ln -sf ../../crypto/asn1/asn1_mac.h ./include/openssl/asn1_mac.h
ln -sf ../../crypto/asn1/asn1t.h ./include/openssl/asn1t.h
ln -sf ../../crypto/bio/bio.h ./include/openssl/bio.h
ln -sf ../../crypto/bf/blowfish.h ./include/openssl/blowfish.h
ln -sf ../../crypto/bn/bn.h ./include/openssl/bn.h
ln -sf ../../crypto/buffer/buffer.h ./include/openssl/buffer.h
ln -sf ../../crypto/cast/cast.h ./include/openssl/cast.h
ln -sf ../../crypto/comp/comp.h ./include/openssl/comp.h
ln -sf ../../crypto/conf/conf_api.h ./include/openssl/conf_api.h
ln -sf ../../crypto/conf/conf.h ./include/openssl/conf.h
ln -sf ../../crypto/crypto.h ./include/openssl/crypto.h
ln -sf ../../crypto/des/des.h ./include/openssl/des.h
ln -sf ../../crypto/des/des_old.h ./include/openssl/des_old.h
ln -sf ../../crypto/dh/dh.h ./include/openssl/dh.h
ln -sf ../../crypto/dsa/dsa.h ./include/openssl/dsa.h
ln -sf ../../crypto/dso/dso.h ./include/openssl/dso.h
ln -sf ../../ssl/dtls1.h ./include/openssl/dtls1.h
ln -sf ../../crypto/ebcdic.h ./include/openssl/ebcdic.h
ln -sf ../../crypto/ecdh/ecdh.h ./include/openssl/ecdh.h
ln -sf ../../crypto/ecdsa/ecdsa.h ./include/openssl/ecdsa.h
ln -sf ../../crypto/ec/ec.h ./include/openssl/ec.h
ln -sf ../../crypto/engine/engine.h ./include/openssl/engine.h
ln -sf ../../e_os2.h ./include/openssl/e_os2.h
ln -sf ../../crypto/err/err.h ./include/openssl/err.h
ln -sf ../../crypto/evp/evp.h ./include/openssl/evp.h
ln -sf ../../crypto/hmac/hmac.h ./include/openssl/hmac.h
ln -sf ../../crypto/idea/idea.h ./include/openssl/idea.h
ln -sf ../../crypto/krb5/krb5_asn.h ./include/openssl/krb5_asn.h
ln -sf ../../ssl/kssl.h ./include/openssl/kssl.h
ln -sf ../../crypto/lhash/lhash.h ./include/openssl/lhash.h
ln -sf ../../crypto/md2/md2.h ./include/openssl/md2.h
ln -sf ../../crypto/md4/md4.h ./include/openssl/md4.h
ln -sf ../../crypto/md5/md5.h ./include/openssl/md5.h
ln -sf ../../crypto/objects/objects.h ./include/openssl/objects.h
ln -sf ../../crypto/objects/obj_mac.h ./include/openssl/obj_mac.h
ln -sf ../../crypto/ocsp/ocsp.h ./include/openssl/ocsp.h
ln -sf ../../crypto/opensslconf.h ./include/openssl/opensslconf.h
ln -sf ../../crypto/opensslv.h ./include/openssl/opensslv.h
ln -sf ../../crypto/ossl_typ.h ./include/openssl/ossl_typ.h
ln -sf ../../crypto/pem/pem2.h ./include/openssl/pem2.h
ln -sf ../../crypto/pem/pem.h ./include/openssl/pem.h
ln -sf ../../crypto/pkcs12/pkcs12.h ./include/openssl/pkcs12.h
ln -sf ../../crypto/pkcs7/pkcs7.h ./include/openssl/pkcs7.h
ln -sf ../../crypto/pqueue/pq_compat.h ./include/openssl/pq_compat.h
ln -sf ../../crypto/pqueue/pqueue.h ./include/openssl/pqueue.h
ln -sf ../../crypto/rand/rand.h ./include/openssl/rand.h
ln -sf ../../crypto/rc2/rc2.h ./include/openssl/rc2.h
ln -sf ../../crypto/rc4/rc4.h ./include/openssl/rc4.h
ln -sf ../../crypto/ripemd/ripemd.h ./include/openssl/ripemd.h
ln -sf ../../crypto/rsa/rsa.h ./include/openssl/rsa.h
ln -sf ../../crypto/stack/safestack.h ./include/openssl/safestack.h
ln -sf ../../crypto/sha/sha.h ./include/openssl/sha.h
ln -sf ../../ssl/ssl23.h ./include/openssl/ssl23.h
ln -sf ../../ssl/ssl2.h ./include/openssl/ssl2.h
ln -sf ../../ssl/ssl3.h ./include/openssl/ssl3.h
ln -sf ../../ssl/ssl.h ./include/openssl/ssl.h
ln -sf ../../crypto/stack/stack.h ./include/openssl/stack.h
ln -sf ../../crypto/store/store.h ./include/openssl/store.h
ln -sf ../../crypto/symhacks.h ./include/openssl/symhacks.h
ln -sf ../../ssl/tls1.h ./include/openssl/tls1.h
ln -sf ../../crypto/tmdiff.h ./include/openssl/tmdiff.h
ln -sf ../../crypto/txt_db/txt_db.h ./include/openssl/txt_db.h
ln -sf ../../crypto/ui/ui_compat.h ./include/openssl/ui_compat.h
ln -sf ../../crypto/ui/ui.h ./include/openssl/ui.h
ln -sf ../../crypto/x509/x509.h ./include/openssl/x509.h
ln -sf ../../crypto/x509v3/x509v3.h ./include/openssl/x509v3.h
ln -sf ../../crypto/x509/x509_vfy.h ./include/openssl/x509_vfy.h
ln -sf ../crypto/bf/bftest.c ./test/bftest.c
ln -sf ../crypto/bn/bntest.c ./test/bntest.c
ln -sf ../crypto/cast/casttest.c ./test/casttest.c
ln -sf ../crypto/des/destest.c ./test/destest.c
ln -sf ../crypto/dh/dhtest.c ./test/dhtest.c
ln -sf ../crypto/dsa/dsatest.c ./test/dsatest.c
ln -sf ../crypto/ecdh/ecdhtest.c ./test/ecdhtest.c
ln -sf ../crypto/ecdsa/ecdsatest.c ./test/ecdsatest.c
ln -sf ../crypto/ec/ectest.c ./test/ectest.c
ln -sf ../crypto/engine/enginetest.c ./test/enginetest.c
ln -sf ../crypto/evp/evp_test.c ./test/evp_test.c
ln -sf ../crypto/bn/exptest.c ./test/exptest.c
ln -sf ../crypto/hmac/hmactest.c ./test/hmactest.c
ln -sf ../crypto/idea/ideatest.c ./test/ideatest.c
ln -sf ../crypto/md2/md2test.c ./test/md2test.c
ln -sf ../crypto/md4/md4test.c ./test/md4test.c
ln -sf ../crypto/md5/md5test.c ./test/md5test.c
ln -sf dummytest.c ./test/mdc2test.c
ln -sf ../crypto/rand/randtest.c ./test/randtest.c
ln -sf ../crypto/rc2/rc2test.c ./test/rc2test.c
ln -sf ../crypto/rc4/rc4test.c ./test/rc4test.c
ln -sf dummytest.c ./test/rc5test.c
ln -sf ../crypto/ripemd/rmdtest.c ./test/rmdtest.c
ln -sf ../crypto/rsa/rsa_test.c ./test/rsa_test.c
ln -sf ../crypto/sha/sha1test.c ./test/sha1test.c
ln -sf ../crypto/sha/sha256t.c ./test/sha256t.c
ln -sf ../crypto/sha/sha512t.c ./test/sha512t.c
ln -sf ../crypto/sha/shatest.c ./test/shatest.c
ln -sf ../ssl/ssltest.c ./test/ssltest.c
